### ISSUE TITLE
Training Cron not running?

### ISSUE THREAD

**Issue by ListerOsmeg** [bpkennedy/shockball2#108]
## Expected Behavior
Training schedule to clear and stats change

## Actual Behavior
Everything is the same as the day before

## Steps to Reproduce the Problem
Select a training regime and wait a day

  1.
  2.
  3.

## Specifications
Chrome/Windows not time dependent

  - Browser: (Chrome, Safari, Firefox, Internet Explorer 11)
  - Device: (ie.  Android, iOS, Mac, Windows)
  - Time discovered: (ie.  about 9am this morning)

**Comment by bpkennedy** [comment]
This was fixed
