### ISSUE TITLE
Can't send contract

### ISSUE THREAD

**Issue by ListerOsmeg** [bpkennedy/shockball2#122]
## Expected Behavior
So I'm offering an NPC a contract, I get the pop up window to enter amount and number of seasons. Entered a value above the minimum and clicked Send Contract, but nothing happens, the button dims when I click it > here I'd expect to move to another screen and have some sort of visual confirmation the contract sent.

## Actual Behavior
So I'm offering an NPC a contract, I get the pop up window to enter amount and number of seasons. Entered a value above the minimum and clicked Send Contract, but nothing happens, the button dims when I click it but that is all. Still on the popup screen.

## Steps to Reproduce the Problem
go to transfer market click an NPC and offer a contract.

## Specifications
W10 Chrome

**Comment by bpkennedy** [comment]
Can you reproduce this now or is it intermittent - or not at all?  @ListerOsmeg
